apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: checkcrowdstrikeagent
spec:
  crd:
    spec:
      names:
        kind: CheckCrowdStrikeAgent
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package checkcrowdstrikeagent

        required_ns := input.parameters.requiredNamespace
        
        # Namespace does not exist 
        violation[{"msg": msg}] { 
          not data.inventory.cluster.v1.Namespace["falcon-system"]
          msg := "CrowdStrike's Namespace does not exist - '%s", [required_ns])
        }

        # Daemonset does not exist
        violation[{"msg": msg}] {
          not data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]
          msg := "CrowdStrike's Daemonset does not exist"
        }

        # Check Daemonset state
        violation[{"msg": msg}] {
          data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]["status"]["numberReady"] != data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]["status"]["desiredNumberScheduled"]
          msg := "CrowdStrike's Daemonset is not in a fully ready state"
        }
