apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sazurenocrowdstrikefalconagents
spec:
  crd:
    spec:
      names:
        kind: K8sAzureNoCrowdStrikeFalconAgents
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            requiredNamespace:
              type: string
              description: "Namespace where CrowdStrike Falcon DaemonSet should be running"
            requiredDaemonSet:
              type: string
              description: "Name of the CrowdStrike Falcon DaemonSet"
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequirecrowdstrikefalcon

        violation[{"msg": msg, "details": {}}] {
          required_ns := input.parameters.requiredNamespace
          required_ds := input.parameters.requiredDaemonSet

          # Tracing instead of print statements
          trace(sprintf("Required Namespace: %v", [required_ns]))
          trace(sprintf("Required DaemonSet: %v", [required_ds]))

          # Check if the required DaemonSet exists
          trace(sprintf("Checking if DaemonSet %v exists in namespace %v", [required_ds, required_ns]))
          not daemonset_exists(required_ns, required_ds)
          msg := sprintf("CrowdStrike Falcon DaemonSet '%s' is required in namespace '%s' but is missing", [required_ds, required_ns])
        }

        daemonset_exists(ns, ds) {
          some i
          d := input.review.object.items[i]
          d.kind == "DaemonSet"
          d.metadata.namespace == ns
          d.metadata.name == ds
        }
