apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireFalconNamespace
metadata:
  name: require-falcon-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system