apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requirefalconnamespace
spec:
  crd:
    spec:
      names:
        kind: RequireFalconNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requirefalconnamespace

        # Namespace does not exist 
        violation[{"msg": msg}] {
          not data.inventory.namespace["falcon-system"]
          msg := "CrowdStrike's Namespace does not exist"
        }

        # Daemonset does not exist
        violation[{"msg": msg}] {
          not data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]
          msg := "CrowdStrike's agent does not exist"
        }

        # Check Daemonset state
        violation[{"msg": msg}] {
          data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]["metadata"]["spec"]["status"]["numberReady"] != data.inventory.namespace["falcon-system"]["apps/v1"].DaemonSet["falcon-sensor"]["metadata"]["spec"]["status"]["desiredNumberScheduled"]
          msg := "CrowdStrike's Daemonset is not in a fully ready state"
        }
