apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requirefalconnamespace
spec:
  crd:
    spec:
      names:
        kind: RequireFalconNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package requirefalconnamespace

        violation[{"msg": msg}] {
          # Get all namespaces
          namespaces := [namespace | input.review.object.kind == "Namespace"; namespace := input.review.object.metadata.name]
          
          # Also check stored namespaces to ensure Falcon namespace exists
          existing_namespaces := [data.inventory.cluster.v1.Namespace[ns].metadata.name | ns]
          
          # Combine all known namespaces
          all_namespaces := array.concat(namespaces, existing_namespaces)
          
          # Check if any namespace contains "falcon-system"
          not any_falcon_namespace(all_namespaces)
          
          msg := "Violation: 'falcon-system' does not exist"
        }
        
        any_falcon_namespace(namespaces) {
          namespace := namespaces[_]
          contains(lower(namespace), "falcon-system")
        }